return {
	"ibhagwan/fzf-lua",
	-- optional for icon support
	dependencies = { "nvim-tree/nvim-web-devicons" },
	-- or if using mini.icons/mini.nvim
	-- dependencies = { "echasnovski/mini.icons" },
	opts = {
		colorschemes = {
			ignore_patterns = {
				"^delek$",
				"^blue$",
				"^darkblue$",
				"^desert$",
				"^elflord$",
				"^evening$",
				"^habamax$",
				"^industry$",
				"^koehler$",
				"^lunaperche$",
				"^morning$",
				"^murphy$",
				"^pablo$",
				"^peachpuff$",
				"^quiet$",
				"^retrobox$",
				"^ron$",
				"^shine$",
				"^slate$",
				"^$",
				"^sorbet$",
				"^torte$",
				"^unokai$",
				"^vim$",
				"^wildcharm$",
				"^zaibatsu$",
				"^zellner$",
				"^catppuccin-macchiato$",
				"^catppuccin-latte$",
				"^catppuccin-mocha$",
				"^catppuccin-frappe$",
				"^$",
			},
		},
		awesome_colorschemes = {
			live_preview = true,
		},
	},
}
