-- src/packages/neovim/ight/__config/lua/fzf-lua.lua
require("fzf-lua").setup({
		colorschemes = {
			ignore_patterns = {
				"^delek$",
				"^blue$",
				"^darkblue$",
				"^desert$",
				"^elflord$",
				"^evening$",
				"^habamax$",
				"^industry$",
				"^koehler$",
				"^lunaperche$",
				"^morning$",
				"^murphy$",
				"^pablo$",
				"^peachpuff$",
				"^quiet$",
				"^retrobox$",
				"^ron$",
				"^shine$",
				"^slate$",
				"^$",
				"^sorbet$",
				"^torte$",
				"^unokai$",
				"^vim$",
				"^wildcharm$",
				"^zaibatsu$",
				"^zellner$",
				"^catppuccin-macchiato$",
				"^catppuccin-latte$",
				"^catppuccin-mocha$",
				"^catppuccin-frappe$",
				"^$",
			},
		},
		awesome_colorschemes = {
			live_preview = true,
		},
})
